# Generated by Django 3.1.7 on 2021-05-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synchronization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
