# Generated by Django 3.1.7 on 2021-05-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronization',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synchronization',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
