# Generated by Django 3.1.7 on 2021-06-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20210605_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronization',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='synchronization',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='В процессе'),
        ),
        migrations.AlterField(
            model_name='synchronization',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='synchronization',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Успешно'),
        ),
    ]
