version: "3"

services:
  nginx:
    build: ./nginx
    container_name: byled-local-nginx
    restart: always
    ports:
      - 8009:80
    depends_on:
      - web
  db:
    image: postgres:13.2
    container_name: byled-local-db
    restart: always
    volumes:
      - /home/katskov-tech-server/projects/byled/.docker/db:/var/lib/postgresql/data
    env_file:
      /home/katskov-tech-server/projects/byled/.env
    ports:
      - 8010:5432
  web:
    container_name: byled-local-web
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    env_file:
      /home/katskov-tech-server/projects/byled/.env
    command: bash -c "python3 ./byled/manage.py migrate && python3 ./byled/manage.py runserver 0.0.0.0:80"
      - /home/katskov-tech-server/projects/byled/.docker/logs:/code/logs
      - /home/katskov-tech-server/projects/byled/uploads:/code/byled/uploads/products
    depends_on:
      - db
  celery-worker:
    restart: always
    container_name: byled-local-celery-worker
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    env_file:
      /home/katskov-tech-server/projects/byled/.env
    command: bash -c "cd byled && celery -A byled worker"
    volumes:
      - /home/katskov-tech-server/projects/byled/.docker/logs:/code/logs
      - /home/katskov-tech-server/projects/byled/uploads:/code/byled/uploads/products
    depends_on:
      - db
  celery-beat:
    restart: always
    container_name: byled-local-celery-beat
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    env_file:
      /home/katskov-tech-server/projects/byled/.env
    command: bash -c "cd byled && celery -A byled beat"
    volumes:
      - /home/katskov-tech-server/projects/byled/.docker/logs:/code/logs
      - /home/katskov-tech-server/projects/byled/uploads:/code/byled/uploads/products
    depends_on:
      - db
  rabbitmq:
    restart: always
    image: rabbitmq:3.8-management
    container_name: byled-local-rabbitmq
    volumes:
      - /home/katskov-tech-server/projects/byled/.docker/rabbitmq:/bitnami
    ports:
      - 15673:15672
