# Generated by Django 3.1.7 on 2021-06-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='file',
            name='metatag',
            field=models.CharField(default='', max_length=255, verbose_name='Метатэг'),
            preserve_default=False,
        ),
    ]
