# Generated by Django 3.1.7 on 2021-05-17 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0022_auto_20210517_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_exported', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан в')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен в')),
                ('status', models.CharField(choices=[('COMPLETED', 'Выполнен'), ('IN_PROGRESS', 'В Работе'), ('DRAFT', 'ЧЕРНОВИК'), ('CANCELED', 'ОТКЛОНЕН')], default='DRAFT', max_length=11, verbose_name='Статус заказа')),
                ('reason_of_refuse', models.TextField(blank=True, verbose_name='Причина отклонения проекта')),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_of_order', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Место в иерархии')),
                ('is_visible', models.BooleanField(default=True)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Место в иерархии')),
                ('products', models.ManyToManyField(blank=True, default=None, related_name='areasproducts', to='store.Product', verbose_name='Товары')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.room', verbose_name='Помещение')),
            ],
        ),
    ]
