# Generated by Django 3.1.7 on 2021-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_exported',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Выполнен'), ('IN_PROGRESS', 'В Работе'), ('DRAFT', 'ЧЕРНОВИК'), ('CANCELED', 'ОТКЛОНЕН')], default='DRAFT', max_length=11, verbose_name='Статус заказа'),
        ),
    ]
