# Generated by Django 3.1.7 on 2021-05-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210518_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaitem',
            name='area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.area', verbose_name='Корзины'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Место в иерархии'),
        ),
    ]
