# Generated by Django 3.1.7 on 2021-05-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210517_1614'),
        ('projects', '0005_auto_20210519_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaitem',
            name='product',
        ),
        migrations.AddField(
            model_name='areaitem',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар'),
        ),
    ]
