# Generated by Django 3.1.7 on 2021-05-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210519_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaitem',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, max_length=100, verbose_name='Скидка'),
        ),
    ]
