# Generated by Django 3.1.7 on 2021-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210519_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaitem',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
    ]
