# Generated by Django 3.1.7 on 2021-06-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210605_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес клиента'),
        ),
    ]
