# Generated by Django 3.1.7 on 2021-07-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210709_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-create_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
