# Generated by Django 3.1.7 on 2021-08-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210730_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Скидка в % на весь проект'),
        ),
    ]
