# Generated by Django 3.1.7 on 2021-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210811_1037'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['id'], name='projects_ar_id_5b26a5_idx'),
        ),
        migrations.AddIndex(
            model_name='areaitem',
            index=models.Index(fields=['id'], name='projects_ar_id_2591d0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id'], name='projects_pr_id_a18e17_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['id'], name='projects_ro_id_29382a_idx'),
        ),
    ]
