# Generated by Django 3.1.7 on 2023-03-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210811_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaitem',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена'),
        ),
    ]
