# Generated by Django 3.1.7 on 2023-03-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20230325_1115'),
    ]

    operations = [
    ]
