# Generated by Django 3.1.7 on 2023-03-26 06:19
from typing import Optional

from django.db import migrations, models
from users.models import User as UserModel

class Currencies(object):
    byn = 'BYN'
    rub = 'RUB'








def update_custom_prices(apps, schema_editor):
    ProductPrice = apps.get_model('store', 'ProductPrice')
    PriceLevel = apps.get_model('store', 'PriceLevel')
    AreaItem = apps.get_model('projects', 'AreaItem')
    User = apps.get_model('users', 'User')

    PRICE_LEVEL_MAP = {
        Currencies.byn: {
            UserModel.PriceLevels.OPT1: "5c94e005-00f2-11eb-bab4-4ccc6a42cb23",
            UserModel.PriceLevels.OPT2: "691c60d0-00f2-11eb-bab4-4ccc6a42cb23",
            UserModel.PriceLevels.OPT3: "734541dd-00f2-11eb-bab4-4ccc6a42cb23",
            UserModel.PriceLevels.OPT4: "734541de-00f2-11eb-bab4-4ccc6a42cb23",
            UserModel.PriceLevels.RETAIL_NO_NDS: "5c94e004-00f2-11eb-bab4-4ccc6a42cb23",
            UserModel.PriceLevels.RETAIL_NDS: "4371e6c0-00f2-11eb-bab4-4ccc6a42cb23",
        },
        Currencies.rub: {
            UserModel.PriceLevels.OPT1: "2121ed13-3995-11ed-bb2d-4ccc6a42cb23",
            UserModel.PriceLevels.OPT2: "30a27061-3995-11ed-bb2d-4ccc6a42cb23",
            UserModel.PriceLevels.OPT3: "47b32be1-3995-11ed-bb2d-4ccc6a42cb23",
            UserModel.PriceLevels.OPT4: "47b32be2-3995-11ed-bb2d-4ccc6a42cb23",
            UserModel.PriceLevels.RETAIL_NO_NDS: "5bed9d7f-3995-11ed-bb2d-4ccc6a42cb23",
            UserModel.PriceLevels.RETAIL_NDS: "4e8c5018-3a48-11ed-bb2d-4ccc6a42cb23",
        }
    }

    def get_price_level(user_price_level, currency=Currencies.byn) -> Optional[PriceLevel]:
        """
        Возвращает объект модели PriceLevel исходя из уровня цены пользователя и указаной валюты (currency)
        :param user_price_level:
        :param currency:
        :return:
        """
        if currency not in PRICE_LEVEL_MAP:
            return None
        if user_price_level not in PRICE_LEVEL_MAP.get(currency):
            return None
        return PriceLevel.objects.get(id=PRICE_LEVEL_MAP.get(currency).get(user_price_level))

    for area_item in AreaItem.objects.all():
        project = area_item.area.room.project
        user = project.client or project.owner
        for currency in [Currencies.byn, Currencies.rub]:
            if user:
                price_level = get_price_level(user.price_level, currency)
                product_price: ProductPrice = ProductPrice.objects.filter(
                    price_level=price_level,
                    product=area_item.product_id,
                ).first()
                if product_price:
                    if currency == Currencies.byn:
                        area_item.price_byn = product_price.price
                    elif currency == Currencies.rub:
                        area_item.price_rub = product_price.price
                    area_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20230326_0855'),
    ]

    operations = [
        migrations.RunPython(update_custom_prices)
    ]
