# Generated by Django 3.1.7 on 2021-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210511_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='blog.Categories', verbose_name='Категории'),
        ),
    ]
