# Generated by Django 3.1.7 on 2021-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210511_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название категории'),
        ),
    ]
