# Generated by Django 3.1.7 on 2021-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210615_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='picture',
            field=models.URLField(blank=True, default=None, max_length=255, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.URLField(blank=True, default=None, max_length=255, null=True, verbose_name='Аватар'),
        ),
    ]
