# Generated by Django 3.1.7 on 2021-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210617_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Изображение'),
        ),
    ]
