# Generated by Django 3.1.7 on 2021-03-19 15:46

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_restore_keys'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restore_keys',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
