# Generated by Django 3.1.7 on 2021-03-19 16:24

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210319_1846'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restore_keys',
            managers=[
                ('objects', users.models.KeyManager()),
            ],
        ),
    ]
