# Generated by Django 3.1.7 on 2021-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20210319_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Мэнеджер'), ('ADMIN', 'Администратор')],
                                   default='CLIENT', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='price_level',
            field=models.CharField(
                choices=[('LV1', 'Уровень 1'), ('LV2', 'Уровень 2'), ('LV3', 'Уровень 3'), ('LV4', 'Уровень 4'),
                         ('LV5', 'Уровень 5')], default='LV1', max_length=3),
        ),
    ]
