# Generated by Django 3.1.7 on 2021-04-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210418_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionkey',
            options={'verbose_name': 'Секретный ключ', 'verbose_name_plural': 'Секретные ключи'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
