# Generated by Django 3.1.7 on 2021-04-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210418_1928'),
        ('users', '0014_auto_20210418_1110'),
    ]

    operations = [
    ]
