# Generated by Django 3.1.7 on 2021-04-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20210421_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Мэнеджер'), ('ADMIN', 'Администратор')], default='CLIENT', max_length=7, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_level',
            field=models.CharField(blank=True, choices=[('LV1', 'Уровень 1'), ('LV2', 'Уровень 2'), ('LV3', 'Уровень 3'), ('LV4', 'Уровень 4'), ('LV5', 'Уровень 5')], default='LV1', max_length=3, verbose_name='Уровень цены'),
        ),
    ]
