# Generated by Django 3.1.7 on 2021-04-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_client'),
        ('users', '0018_auto_20210426_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
