# Generated by Django 3.1.7 on 2021-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_client'),
        ('users', '0020_auto_20210427_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(default=None, null=True, to='store.Product'),
        ),
    ]
