# Generated by Django 3.1.7 on 2021-04-27 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_client'),
        ('users', '0021_auto_20210427_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basket',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(default=None, to='store.Product'),
        ),
    ]
