# Generated by Django 3.1.7 on 2021-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210428_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ManyToManyField(default=None, to='users.Basket'),
        ),
    ]
