# Generated by Django 3.1.7 on 2021-05-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210517_1614'),
        ('users', '0029_auto_20210511_2149'),
    ]

    operations = [
    ]
