# Generated by Django 3.1.7 on 2021-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_merge_20210521_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default=None, max_length=255, null=True, verbose_name='Аватар'),
        ),
    ]
