# Generated by Django 3.1.7 on 2021-10-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210730_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price_level',
            field=models.CharField(blank=True, choices=[('LV1', 'Уровень 1'), ('LV2', 'Уровень 2'), ('LV3', 'Уровень 3'), ('LV4', 'Уровень 4'), ('LV5', 'Уровень 5')], default='LV1', max_length=3, null=True, verbose_name='Уровень цены'),
        ),
    ]
