# Generated by Django 3.1.7 on 2021-10-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20211020_0857'),
        ('users', '0034_auto_20211020_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pricelevel', verbose_name='Уровень цены'),
        ),
    ]
