# Generated by Django 3.1.7 on 2022-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20211020_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unp',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UNP'),
        ),
    ]
