# Generated by Django 3.1.7 on 2022-09-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_unp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unp',
        ),
    ]
