# Generated by Django 3.1.7 on 2022-11-17 20:14

from django.db import migrations, models

def save_users_price_levels(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        price_level = user.price_level
        if price_level is not None:
            print(price_level.name)
            if price_level.id == '5c94e005-00f2-11eb-bab4-4ccc6a42cb23':
                user.price_level_new = 'OPT1'
            if price_level.id == '691c60d0-00f2-11eb-bab4-4ccc6a42cb23':
                user.price_level_new = 'OPT2'
            if price_level.id == '734541dd-00f2-11eb-bab4-4ccc6a42cb23':
                user.price_level_new = 'OPT3'
            if price_level.id == '734541de-00f2-11eb-bab4-4ccc6a42cb23':
                user.price_level_new = 'OPT4'
            if price_level.id == '4371e6c0-00f2-11eb-bab4-4ccc6a42cb23':
                user.price_level_new = 'RETAIL_NDS'
            if price_level.id == '5c94e004-00f2-11eb-bab4-4ccc6a42cb23':
                user.price_level_new = 'RETAIL_NO_NDS'
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_user_unp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price_level_new',
            field=models.CharField(blank=True, choices=[('OPT1', 'Опт 1'), ('OPT2', 'Опт 2'), ('OPT3', 'Опт 3'), ('OPT4', 'Опт 4'), ('RETAIL_NDS', 'Розница с НДС'), ('RETAIL_NO_NDS', 'Розница без НДС')], default=None, max_length=13, null=True, verbose_name='Уровень цены Yjdsq'),
        ),
        migrations.RunPython(save_users_price_levels)
    ]
