# Generated by Django 3.1.7 on 2022-11-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_price_level_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='price_level',
        ),
    ]
