# Generated by Django 3.1.7 on 2022-11-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_user_price_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='price_level_new',
            new_name='price_level',
        ),
    ]
