# Generated by Django 3.1.7 on 2022-11-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20221117_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price_level',
            field=models.CharField(blank=True, choices=[('OPT1', 'Уровень 1'), ('OPT2', 'Уровень 2'), ('OPT3', 'Уровень 3'), ('OPT4', 'Уровень 4'), ('RETAIL_NDS', 'Розница с НДС'), ('RETAIL_NO_NDS', 'Розница без НДС')], default=None, max_length=13, null=True, verbose_name='Уровень цены'),
        ),
    ]
