# Generated by Django 3.1.7 on 2021-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('power_output', models.IntegerField(blank=True)),
                ('voltage', models.SmallIntegerField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=1, max_digits=7)),
                ('grade_of_waterproofment', models.CharField(blank=True, max_length=7)),
                ('warranty', models.SmallIntegerField(blank=True)),
                ('product_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
