# Generated by Django 3.1.7 on 2021-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_auto_20210416_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Номер телефона')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('social_network', models.CharField(max_length=15, verbose_name='Мессенджер клиента')),
                ('company_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес компании')),
                ('cost', models.IntegerField(blank=True, verbose_name='Цена')),
                ('grade_of_waterproofment',
                 models.CharField(blank=True, max_length=7, verbose_name='Степень влагозащиты')),
                ('warranty', models.SmallIntegerField(blank=True, verbose_name='Гарантия')),
                ('product_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код товара')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade_of_waterproofment',
            field=models.CharField(blank=True, max_length=7, verbose_name='Степень влагозащиты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_output',
            field=models.IntegerField(blank=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltage',
            field=models.SmallIntegerField(blank=True, verbose_name='Напряжение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.SmallIntegerField(blank=True, verbose_name='Гарантия'),
        ),
    ]
