# Generated by Django 3.1.7 on 2021-05-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210507_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
