# Generated by Django 3.1.7 on 2021-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210508_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
