# Generated by Django 3.1.7 on 2021-05-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210510_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_output',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.FloatField(default=0.0, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Брэнд'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текстовое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='group_of_list',
            field=models.CharField(blank=True, max_length=255, verbose_name='Группа списка'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_fan',
            field=models.BooleanField(default=False, verbose_name='Наличие вентилятора'),
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='led_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество светодиодов'),
        ),
        migrations.AddField(
            model_name='product',
            name='led_size',
            field=models.FloatField(default=0.0, verbose_name='Размер светодиодов'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=0.0, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='light_flow',
            field=models.FloatField(default=0.0, verbose_name='Световой поток, Лм'),
        ),
        migrations.AddField(
            model_name='product',
            name='output_current',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Выходной ток, А'),
        ),
        migrations.AddField(
            model_name='product',
            name='output_voltage',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Выходное напряжение, В'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, max_length=255, verbose_name='Используемые упаковки'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.IntegerField(blank=True, default=0, verbose_name='Мощность, Вт'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_by_1m',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Мощность 1м, Вт'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='scattering_angle',
            field=models.FloatField(default=0.0, verbose_name='Угол рассеивания'),
        ),
        migrations.AddField(
            model_name='product',
            name='segment_size',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Размер сегмента, мм'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое наименование'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='0x0x0', max_length=255, verbose_name='Размеры (ДхШхВ), мм'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='Единица хранения'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип номенклатуры'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(default=0.0, verbose_name='Ставка НДС, %'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.FloatField(default=0.0, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='product',
            name='wire_length',
            field=models.FloatField(default=0.0, verbose_name='Длинна провода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltage',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Рабочее напряжение, В'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, default=0, verbose_name='Гарантия, мес'),
        ),
    ]
