# Generated by Django 3.1.7 on 2021-05-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210510_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_1c',
            field=models.CharField(default='', max_length=255, verbose_name='ID 1C'),
        ),
    ]
