# Generated by Django 3.1.7 on 2021-05-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_id_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_1c',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID 1C'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.FloatField(blank=True, default=0, verbose_name='Мощность, Вт'),
        ),
    ]
