# Generated by Django 3.1.7 on 2021-05-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210510_0436'),
        ('store', '0022_auto_20210511_2149'),
    ]

    operations = [
    ]
