# Generated by Django 3.1.7 on 2021-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210517_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
    ]
