# Generated by Django 3.1.7 on 2021-05-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210520_1329'),
        ('store', '0023_merge_20210521_1547'),
    ]

    operations = [
    ]
