# Generated by Django 3.1.7 on 2021-06-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210618_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archive',
            field=models.BooleanField(default=True, verbose_name='Архивный (не отображается в прайс листе)'),
        ),
    ]
