# Generated by Django 3.1.7 on 2021-07-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Категория'),
        ),
    ]
