# Generated by Django 3.1.7 on 2021-08-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210803_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на изображение'),
        ),
    ]
