# Generated by Django 3.1.7 on 2021-08-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Артикул'),
        ),
    ]
