# Generated by Django 3.1.7 on 2021-10-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_pricelevel_productprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(related_name='products', to='store.ProductPrice'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена'),
        ),
    ]
