# Generated by Django 3.1.7 on 2021-10-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20211026_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pricelevel', verbose_name='Уровень цены'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар'),
        ),
    ]
