# Generated by Django 3.1.7 on 2023-03-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20220927_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_byn',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена (byn)'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_ryb',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена (ryb)'),
        ),
    ]
