# Generated by Django 3.1.7 on 2023-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20230325_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='price_byn',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='price_ryb',
        ),
        migrations.AddField(
            model_name='productprice',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена'),
        ),
    ]
