# Generated by Django 3.1.7 on 2023-03-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_productprice_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Цена товара', 'verbose_name_plural': 'Цены товаров'},
        ),
    ]
