# Generated by Django 3.1.7 on 2023-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_auto_20230326_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
